version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - run: pwd
      - run: cd project
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run: yarn
      - run: |
          pwd
          yarn test
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
  e2e:
    docker:
      - image: circleci/node:8.11-browsers
    steps:
      - run: echo "Saved for e2e Tests"
workflows:
  version: 2
  all_tests:
    jobs:
      - test
      - e2e